---
title: "Extração de dados da Base de CNPJ da Receita Federal"
author: Bruno Soares, Luiz Batista, Lucas Vieira, Isabella Teixeira
date:   07/05/2020
output: html_document
dataAddress: http://receita.economia.gov.br/orientacao/tributaria/cadastros/cadastro-nacional-de-pessoas-juridicas-cnpj/dados-publicos-cnpj
---

#Importação das bibliotecas
```{r}
library(tidyverse)
library(tidyverse)
library(readxl)
library(tidyr)
library(openxlsx)
```

#Leitura das bases de dados
```{r}
# LAYOUT:  http://200.152.38.155/CNPJ/LAYOUT_DADOS_ABERTOS_CNPJ.pdf
dados_Layout  <- read_excel("dados/LAYOUT_DADOS_ABERTOS_CNPJ.xlsx")
# ARQUIVO: "Dados Abertos CNPJ 01"
#baseCNPJ      <- read_lines("dados/K3241.K003200DV.D00422.L00001.txt")
baseCNPJ       <- read_lines("dados/dadosCNPJ01Amostra100.txt")  #Amostra com 100 linhas.
```

#Pegar intervalos da planilha
```{r}
tipo_atual  <- dados_Layout %>% 
  distinct(TIPO_REGISTRO, ID_TIPO_REGISTRO) %>%
    filter(ID_TIPO_REGISTRO==1)   #ou TIPO_REGISTRO=="LAYOUT PRINCIPAL"
```

#Trata dados
```{r}
dados_Layout_por_tipo <- dados_Layout %>% 
  filter(TIPO_REGISTRO == as.character(tipo_atual$TIPO_REGISTRO),POSICAO_R!="NA")   %>% 
  mutate(NOME_REGISTRO=str_replace_all(NOME_REGISTRO," |/|-","_"))  
    # %>%  mutate(NOME_REGISTRO=iconv(str_replace_all(NOME_REGISTRO," |/|-","_"), to="ASCII//TRANSLIT"))  %>%    
  # ESTÁ DANDO ERRO...
  # mutate(COLUNAFIM=COLUNA + QTDE_CARACTERES)
dados_Layout_por_tipo
```


# Seleciona e tabula o LAYOUT PRINCIPAL
```{r}
  
df_baseCNPJ_PRIN <- baseCNPJ[str_detect(baseCNPJ,"^1")] %>% 
  map(~str_sub(.x, 
                  start=t(dados_Layout_por_tipo$COLUNA)[1:(length(t(dados_Layout_por_tipo$COLUNA)))], 
                  end=(t(dados_Layout_por_tipo$POSICAO_R))))%>%
    transpose %>%
      map(as.character) %>%
        set_names(
          t(dados_Layout_por_tipo$NOME_REGISTRO)
        ) %>%
as_tibble # %>% 
  # filter(CODIGO_NATUREZA_JURIDICA=="3069", UF=="RJ") # Descomentar quando estiver utilizando o arquivo completo

```


```{r}
df_baseCNPJ_PRIN %>%  
      write_csv("dados/_df_CNPJ1_full1_Fundv2.csv")
```
